//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamProjectTournamentEntities : DbContext
    {
        public ExamProjectTournamentEntities()
            : base("name=ExamProjectTournamentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAnswer> tblAnswer { get; set; }
        public virtual DbSet<tblJudge> tblJudge { get; set; }
        public virtual DbSet<tblProject> tblProject { get; set; }
        public virtual DbSet<tblQuestionaire> tblQuestionaire { get; set; }
        public virtual DbSet<tblTeam> tblTeam { get; set; }
        public virtual DbSet<tblTournament> tblTournament { get; set; }
    }
}
