//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAnswer
{
    public long fldAnswerID { get; set; }
    public Nullable<long> fldQuestionaireID { get; set; }
    public Nullable<long> fldJudgeID { get; set; }
    public int fldFirstQuestionScore { get; set; }
    public int fldSecondQuestionScore { get; set; }
    public int fldThirdQuestionScore { get; set; }
    public int fldFourthQuestionScore { get; set; }

    public virtual tblJudge tblJudge { get; set; }
    public virtual tblQuestionaire tblQuestionaire { get; set; }
}
