//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuestionaire()
        {
            this.tblAnswer = new HashSet<tblAnswer>();
        }
    
        public long fldQuestionaireID { get; set; }
        public Nullable<int> fldTournamentID { get; set; }
        public string fldFirstQuestion { get; set; }
        public string fldSecondQuestion { get; set; }
        public string fldThirdQuestion { get; set; }
        public string fldFourthQuestion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAnswer> tblAnswer { get; set; }
        public virtual tblTournament tblTournament { get; set; }
    }
}
