//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblTournament
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblTournament()
    {
        this.tblJudge = new HashSet<tblJudge>();
        this.tblProject = new HashSet<tblProject>();
        this.tblQuestionaire = new HashSet<tblQuestionaire>();
    }

    public int fldTournamentID { get; set; }
    public string fldTournamentName { get; set; }
    public Nullable<int> fldYear { get; set; }
    public Nullable<System.DateTime> fldStartDate { get; set; }
    public Nullable<System.DateTime> fldEndDate { get; set; }
    public string fldStartTime { get; set; }
    public string fldAddress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblJudge> tblJudge { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblProject> tblProject { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblQuestionaire> tblQuestionaire { get; set; }
}
